name: PKWSubmissionUtils
version: '${project.version}'
main: xyz.angeloanan.pkwsubmissionutils.Plugin
api-version: '1.20'
load: STARTUP
authors:
  - Falink
website: https://angeloanan.xyz
load-after:
  - name: FastAsyncWorldEdit
    bootstrap: true
dependencies:
  - name: WorldEdit
    required: true
    bootstrap: true
